[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput --clear"

[deploy]
startCommand = "gunicorn weatherproject.wsgi --log-file -"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
