[build]
builder = "nixpacks"
buildCommand = """
mkdir -p staticfiles
python manage.py collectstatic --noinput --clear
"""

[deploy]
startCommand = "gunicorn weatherproject.wsgi --log-file -"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["python39"]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]
